/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Alunos
 */
public class JFrameCadastroCarro extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCadastroCarro
     */
    public JFrameCadastroCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldfabricante = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelCor = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jLabelDescricao = new javax.swing.JLabel();
        jLabelPlaca = new javax.swing.JLabel();
        jLabelChassi = new javax.swing.JLabel();
        jTextFieldChassi = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabelAno = new javax.swing.JLabel();
        jLabelEsta_funcionando = new javax.swing.JLabel();
        jLabelQuantidade_portas = new javax.swing.JLabel();
        jLabelQuantidade_batidas = new javax.swing.JLabel();
        jComboBoxQuantidade_batidas = new javax.swing.JComboBox();
        jComboBoxQuantidade_portas = new javax.swing.JComboBox();
        jLabelRenavam = new javax.swing.JLabel();
        jTextFieldRenavam = new javax.swing.JTextField();
        jLabelTipo_pneu = new javax.swing.JLabel();
        jTextFieldTipo_pneu = new javax.swing.JTextField();
        jLabelPotencia = new javax.swing.JLabel();
        jTextFieldQuilometragem = new javax.swing.JTextField();
        jRadioButtonNao = new javax.swing.JRadioButton();
        jRadioButtonSim = new javax.swing.JRadioButton();
        jLabelQuilometragem = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButtonSimm = new javax.swing.JRadioButton();
        jRadioButtonNaoo = new javax.swing.JRadioButton();
        jSpinnerAno_fabricacao = new javax.swing.JSpinner();
        jFormattedTextFieldPlaca = new javax.swing.JFormattedTextField();
        jTextFieldPotencia = new javax.swing.JTextField();
        jSpinnerAno_lancamento = new javax.swing.JSpinner();
        jLabelAno_fabricacao = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setText("Codígo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 11, 33, 14);

        jLabel2.setText("Nome");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 31, 27, 14);

        jLabel3.setText("Fabricante");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 97, 51, 14);

        jTextFieldfabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldfabricanteActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldfabricante);
        jTextFieldfabricante.setBounds(70, 90, 151, 20);

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNome);
        jTextFieldNome.setBounds(10, 52, 58, 20);

        jLabelCor.setText("Cor");
        jPanel1.add(jLabelCor);
        jLabelCor.setBounds(10, 190, 17, 14);

        jButtonSalvar.setText("Salvar");
        jPanel1.add(jButtonSalvar);
        jButtonSalvar.setBounds(82, 380, 63, 23);

        jButtonCancelar.setText("cancelar");
        jPanel1.add(jButtonCancelar);
        jButtonCancelar.setBounds(151, 380, 73, 23);

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricao);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(230, 270, 166, 96);

        jLabelDescricao.setText("Descrição");
        jPanel1.add(jLabelDescricao);
        jLabelDescricao.setBounds(240, 230, 46, 14);

        jLabelPlaca.setText("Placa");
        jPanel1.add(jLabelPlaca);
        jLabelPlaca.setBounds(105, 31, 25, 14);

        jLabelChassi.setText("Chassi");
        jPanel1.add(jLabelChassi);
        jLabelChassi.setBounds(10, 128, 31, 14);

        jTextFieldChassi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldChassiActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldChassi);
        jTextFieldChassi.setBounds(70, 120, 150, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vermelho", "Laranja", "Amarelo", "Verde", "Azul", "Roxo", "Verde", "Preto", "Cinza", "Azul baby", "Rosa", "Branco" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(10, 209, 72, 20);

        jLabelAno.setText("Ano Lançamento");
        jPanel1.add(jLabelAno);
        jLabelAno.setBounds(210, 190, 100, 14);

        jLabelEsta_funcionando.setText("Esta funcionando");
        jPanel1.add(jLabelEsta_funcionando);
        jLabelEsta_funcionando.setBounds(10, 330, 83, 14);

        jLabelQuantidade_portas.setText("Portas");
        jPanel1.add(jLabelQuantidade_portas);
        jLabelQuantidade_portas.setBounds(250, 50, 31, 14);

        jLabelQuantidade_batidas.setText("Batidas");
        jPanel1.add(jLabelQuantidade_batidas);
        jLabelQuantidade_batidas.setBounds(250, 100, 35, 14);

        jComboBoxQuantidade_batidas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "nenhum", "1", "2", "3", "4", "5", "mais" }));
        jComboBoxQuantidade_batidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxQuantidade_batidasActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxQuantidade_batidas);
        jComboBoxQuantidade_batidas.setBounds(300, 100, 90, 20);

        jComboBoxQuantidade_portas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "4", "6" }));
        jPanel1.add(jComboBoxQuantidade_portas);
        jComboBoxQuantidade_portas.setBounds(300, 50, 90, 20);

        jLabelRenavam.setText("Renavam");
        jPanel1.add(jLabelRenavam);
        jLabelRenavam.setBounds(10, 240, 50, 23);
        jPanel1.add(jTextFieldRenavam);
        jTextFieldRenavam.setBounds(60, 240, 140, 20);

        jLabelTipo_pneu.setText("Pneu");
        jPanel1.add(jLabelTipo_pneu);
        jLabelTipo_pneu.setBounds(10, 270, 24, 20);
        jPanel1.add(jTextFieldTipo_pneu);
        jTextFieldTipo_pneu.setBounds(60, 270, 140, 20);

        jLabelPotencia.setText("Potencia");
        jPanel1.add(jLabelPotencia);
        jLabelPotencia.setBounds(10, 160, 41, 14);
        jPanel1.add(jTextFieldQuilometragem);
        jTextFieldQuilometragem.setBounds(60, 300, 140, 20);

        jRadioButtonNao.setText("Não");
        jRadioButtonNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNaoActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonNao);
        jRadioButtonNao.setBounds(150, 330, 45, 23);

        jRadioButtonSim.setText("Sim");
        jRadioButtonSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSimActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonSim);
        jRadioButtonSim.setBounds(100, 330, 41, 23);

        jLabelQuilometragem.setText("Km");
        jPanel1.add(jLabelQuilometragem);
        jLabelQuilometragem.setBounds(10, 300, 20, 14);

        jLabel11.setText("Permitida Circulação");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(100, 190, 96, 14);

        jRadioButtonSimm.setText("Sim");
        jPanel1.add(jRadioButtonSimm);
        jRadioButtonSimm.setBounds(100, 210, 41, 23);

        jRadioButtonNaoo.setText("Não");
        jPanel1.add(jRadioButtonNaoo);
        jRadioButtonNaoo.setBounds(150, 210, 45, 23);
        jPanel1.add(jSpinnerAno_fabricacao);
        jSpinnerAno_fabricacao.setBounds(310, 210, 80, 20);

        try {
            jFormattedTextFieldPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AAA-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jFormattedTextFieldPlaca);
        jFormattedTextFieldPlaca.setBounds(80, 50, 90, 20);
        jPanel1.add(jTextFieldPotencia);
        jTextFieldPotencia.setBounds(70, 150, 100, 20);
        jPanel1.add(jSpinnerAno_lancamento);
        jSpinnerAno_lancamento.setBounds(310, 190, 80, 20);

        jLabelAno_fabricacao.setText("ano");
        jPanel1.add(jLabelAno_fabricacao);
        jLabelAno_fabricacao.setBounds(250, 210, 18, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldfabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldfabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldfabricanteActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextFieldChassiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldChassiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldChassiActionPerformed

    private void jComboBoxQuantidade_batidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxQuantidade_batidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxQuantidade_batidasActionPerformed

    private void jRadioButtonNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonNaoActionPerformed

    private void jRadioButtonSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCadastroCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxQuantidade_batidas;
    private javax.swing.JComboBox jComboBoxQuantidade_portas;
    private javax.swing.JFormattedTextField jFormattedTextFieldPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAno;
    private javax.swing.JLabel jLabelAno_fabricacao;
    private javax.swing.JLabel jLabelChassi;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelEsta_funcionando;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelPotencia;
    private javax.swing.JLabel jLabelQuantidade_batidas;
    private javax.swing.JLabel jLabelQuantidade_portas;
    private javax.swing.JLabel jLabelQuilometragem;
    private javax.swing.JLabel jLabelRenavam;
    private javax.swing.JLabel jLabelTipo_pneu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonNao;
    private javax.swing.JRadioButton jRadioButtonNaoo;
    private javax.swing.JRadioButton jRadioButtonSim;
    private javax.swing.JRadioButton jRadioButtonSimm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerAno_fabricacao;
    private javax.swing.JSpinner jSpinnerAno_lancamento;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldChassi;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPotencia;
    private javax.swing.JTextField jTextFieldQuilometragem;
    private javax.swing.JTextField jTextFieldRenavam;
    private javax.swing.JTextField jTextFieldTipo_pneu;
    private javax.swing.JTextField jTextFieldfabricante;
    // End of variables declaration//GEN-END:variables
}
